trigger:
  batch: true
  tags:
    include:
    - refs/tags/* 

variables:
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: Amsterdam-App/templates
      ref: refs/tags/1.2.2

pool: containerBuilder

jobs:
  - template: pipelines/acr/jobs.yaml@templates
    parameters:
      imageName: contact 